
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configura Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Instala dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Valida execução com streamlit
      run: |
        streamlit run app.py --server.headless true --server.port 8501 sleep 5
